### ISSUE TITLE
Redis Sentinel support is not working

### ISSUE THREAD

**Issue by skynet2** [jitsucom/jitsu#1002]
## Environment

- **Deploy method**:  kubernetes, image: jitsucom/jitsu
- **Jitsu version**:  for instance `1.43.6`
- **Cloud Provider**: Rancher RKE v1.24.8
- **Docker Params (if deployed with docker)**: 
```      
        - name: REDIS_URL
          value: 'sentinel://mymaster@rfs-redisfailover:26379'
        - name: USER_RECOGNITION_ENABLED
          value: 'true'
        - name: USER_RECOGNITION_REDIS_URL
          value: 'sentinel://mymaster@rfs-redisfailover:26379'
        - name: DOCKER_HOST
          value: 'tcp://localhost:2375'
        - name: SERVER_VOLUMES_WORKSPACE
          value: /tmp/airbyte/
        - name: CLUSTER_ADMIN_TOKEN
          value: xxxxxxxxx
```

## Description
Jitsu does not work with Redis Sentinel, it looks like it does not understand that the connection string is for sentinel, not for plain redis.
![image](https://user-images.githubusercontent.com/3065048/221941082-313565a2-3bfa-472a-9c56-795adc505c7e.png)

failed to ping Redis: redigo: no sentinels available

### Redis sentinel output
redis-cli -h rfs-redisfailover -p 26379
```# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=mymaster,status=ok,address=10.42.1.76:6379,slaves=2,sentinels=3
```

## Steps to reproduce

- setup redis sentinel ( i used redis operator ) https://github.com/spotahome/redis-operator
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
```
