### ISSUE TITLE
Postgres instance not connecting as a source while connects as a destination

### ISSUE THREAD

**Issue by ardabeyazoglu** [jitsucom/jitsu#1009]
## Environment

- **Deploy method**: `docker-compose.yml`
- **Jitsu version**:  for instance `1.44.3`
- **OS**: for instance `Ubuntu 22.04`
- **Cloud Provider**: private cloud - vmware sphere vm
- **Docker Params (if deployed with docker)**: a list of env variables with values (please, hide sensitive credentials!), mapped volumes and ports

```
services:
  backend:
    image: jitsucom/server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_URL=redis://host.docker.internal:11079
      - JITSU_CONFIGURATOR_URL=http://configurator:7000
      - USER_RECOGNITION_ENABLED=true
      - USER_RECOGNITION_REDIS_URL=redis://host.docker.internal:11080
      - USER_RECOGNITION_TTL_MINUTES=7200
      - TERM=xterm-256color
      - JITSU_EXTENDED_TELEMETRY_DISABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/server:/home/eventnative/data/logs
      - ./data/server/config:/home/eventnative/data/config
      - workspace:/home/eventnative/data/airbyte
    networks:
      - main
    ports:
      - 8001:8001
    depends_on:
      - configurator
    restart: always
  configurator:
    image: jitsucom/configurator
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_URL=redis://host.docker.internal:11079
      - JITSU_SERVER_URL=http://backend:8001
      - TERM=xterm-256color
    volumes:
      - ./logs/configurator:/home/configurator/data/logs
      - ./data/configurator/config:/home/configurator/data/config 
    restart: always
    networks:
      - main
    ports:
      - 7000:7000

volumes:
  workspace:
    name: jitsu_workspace

networks:
  main:
```

## Description

I have mysql source, postgres and clickhouse destinations and everything works fine. Now I want to add the same postgres destination instance as also source. I configure source as I did with destination however it throws a "connection attempt failed" error when i click next and doesnt connect to database. It seems strange because the same instance works normally as destination.

## Steps to reproduce

Here is the source config:
![image](https://user-images.githubusercontent.com/1159836/231584748-be808ee8-4666-4c10-92d7-6e79137966e5.png)

And the destination:
![image](https://user-images.githubusercontent.com/1159836/231584894-ebf0fec7-47bb-4e45-a66b-4b27708ade6f.png)

## Expected behavior

It must connect and work as destination works ok.

## Actual behavior

It does not connect and throws an unknown error. Here is the configurator log:

[ERROR]: [response] "/api/v1/sources/test" error: {"message":"Error ID:870d847ebc814a71bd5885aa75996478: State code: 08001; Message: The connection attempt failed.","error":""} from: XXX.XXX.XXX.XXX method: POST

I have a feeling that same instance does not work as source and destination at the same time, but I can't test it because i can't remove the destination on production.
