### ISSUE TITLE
Apache Kafka as source

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#128]
### Problem

Kafka is a very popular message broker system. We want to listen to messages from Kafka's topic.

### Solution

```
sources:
  kafka1:
    type: kafka
    server: "address:port"
    topic: mytopic
    format: json
```

Here's how Kafka should be configured. EventNative should listen to a particular topic and expect messages to be in JSON format (format=json should be the only format we support so far). Events should be processed with the default server-to-server pipeline further
