### ISSUE TITLE
Webhooks destination

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#228]
## Introduction

There're a tons on services such as [Facebook](https://jitsu.com/docs/destinations-configuration/facebook-conversion-api) or [GA](https://jitsu.com/docs/destinations-configuration/google-analytics) which cannot be supported by Jitsu. However,
we can implement a general mechanism to send data to HTTP via templated webhooks

## Solution
Here's a configuration with specification as comments

```yaml
destinations:
  webhook_sample:
    type: webhook
    mode: stream # batch should not be supported
    data_layout:
      table_name_template: #works as yes / no. If evaluated to null data should not go further
    webhook:
      url: https://test.com/{{.event_type}}/ # treat as template. variables from event can be reference here
      method: POST # can be omitted, GET by default
      headers:
        X-Header: value # request headers
      body: > # value as template
        {"value": "{{.event_name}}"}
```

## Implementation details

All HTTP based destinations (Webhooks, GA and Facebook) should re-use (produce) the same low-level structure that should be executed further by common code

```go
type HttpDestination interface {
	GetUrl(event events.Event) string
	GetMethod() string
	GetBody(event events.Event) string
	GetRequestHeaders() map[string]string
}
```
