### ISSUE TITLE
Add column configuration to mappings section

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#308]
### Problem

At the moment, there's one configuration parameter that defines sql type  of the column in DB representation of the event. This parameter is called `type` and is a part of mapping configuration.

Jitsu assumes that every SQL type can be used typecast and table creation both:
 - `CREATE TABLE (a T)`
 - `insert $value::T`

However, this assumption is wrong. One particular case is RedShift and encoding configuration: `varchar(256) encode zstd` can be used as type for table creation (as in `CREATE TABLE ( column varchar(256) encode zstd)` but not for casting (as in `INSERT 'text'::(varchar(256) encode zstd)`)

### Solution

1. Add `column_type` to `data_layout.mappings.fields` configuration. It will be a string with Column configuration expression (e.g. `column_type: varchar(256) encode zstd`). 
2. Use `column_type` on creating tables in `adapters`.
3. If `column_type` is empty -> get `type` from mappings. 
4. If `type` in mappings is empty -> get the type from value (like it is implemented now)
5. In inserts typecasts statements `type` still must be used.

Mappings configuration example:

```
destinations:
  redshift:
    mode: stream
    datasource:
     ...
    data_layout:
      mappings:
        fields:
          - src: /field1
            dst: /field2
            type: varchar(512)
            column_type: varchar(512) encode zstd
            action: move
        ...
```
