### ISSUE TITLE
Providing multiple configurations for Singer for a single source

### ISSUE THREAD

**Issue by azhard4int** [jitsucom/jitsu#355]
### Problem

What problem this feature is going to solve. Why this problem is important

As of now, Singer as a source provides a configuration that can be used for a single account. In our current application, multiple customers can have their Facebook account integration. 

As from the example of the Singer.

```
 jitsu_singer_facebook:
    type: singer
    destinations: [ "postgres_destination_id" ]
    config:
      tap: tap-facebook
      config: /home/eventnative/data/config/facebook_config.json
      properties: /home/eventnative/data/config/facebook_props.json
      initial_state: /home/eventnative/data/config/facebook_initial_state.json
```

### Solution

Proposed solution: architecture, implementation details etc

There could be two ways for this to implement:

1. Providing a list of array of configurations through which the data should be populated.
2. An HTTP Get Request that could take the list of the configurations.

Example for providing a list of configuration in the form of an array:

```
 jitsu_singer_facebook:
    type: singer
    destinations: [ "postgres_destination_id" ]
    configs:
      -  tap: tap-facebook
         config: /home/eventnative/data/config/facebook_config.json
         properties: /home/eventnative/data/config/facebook_props.json
         initial_state: /home/eventnative/data/config/facebook_initial_state.json
     
```

For the HTTP Request

```
jitsu_singer_facebook:
    type: singer
    destinations: [ "postgres_destination_id" ]
    config:
      tap: tap-facebook
      config: https://mydomain.com/singer/tap/facebook.config.json
      properties: https://mydomain.com/singer/tap/facebook_props.config.json
      initial_state: https://mydomain.com/singer/tap/facebook_initial.config.json
```

If the JSON contains a list of an array for the singer configurations, it could iterate and ETL data. 

P.S I have gone through the Singer.io docs, it is mainly aiming for the single config per account, but would be nice to have an additional feature for Jitsu that covers multiple accounts from a single singer tap.
