### ISSUE TITLE
Allow bq_dataset to use template

### ISSUE THREAD

**Issue by ajimix** [jitsucom/jitsu#383]
### Problem

Datasets are very useful to namespace different things (for example domains) in Google Bigquery. At the moment the dataset is a static string so if you want to use for example a dataset per host, you need to create multiple destinations manually.

### Solution

Allow to use the same template variables as `table_name_template` but for `bq_dataset`.

So you can do something like this:

```yaml
data_layout:
  table_name_template: '{{.event_type}}'
  google:
    bq_dataset: '{{.doc_host}}'
```
