### ISSUE TITLE
Too many colons in address | Redis issue

### ISSUE THREAD

**Issue by siddug** [jitsucom/jitsu#434]
## Description
I am receiving "too many colons in address" error when using Azure Redis (which has the format :password@host:port)

## Steps to reproduce

    jitsu:
        container_name: jitsu
        image: jitsucom/jitsu:latest
        environment:
            - REDIS_URL=":password@host:port"
        volumes:
            - ./compose-data/configurator/data/logs:/home/configurator/data/logs
            - ./compose-data/server/data/logs:/home/eventnative/data/logs
        restart: always
        ports:
            - "8000:8000"

## Expected behavior

Workign Jitsu

## Actual behavior

Error testing Redis connection: dial tcp: address, too many colons in address

Any help is super appreciated. Thanks!

**Comment by siddug** [comment]
Tried it with REDIS_URL="redis://:password@host:port" as well.

Same issue.

**Comment by xtreding** [comment]
Hi @siddug! Thank you for the issue!
Please delete quotes in `REDIS_URL` env value and try:

```
jitsu:
    container_name: jitsu
    image: jitsucom/jitsu:latest
    environment:
        - REDIS_URL=redis://:password@host:port
    volumes:
        - ./compose-data/configurator/data/logs:/home/configurator/data/logs
        - ./compose-data/server/data/logs:/home/eventnative/data/logs
    restart: always
    ports:
        - "8000:8000"
```
