### ISSUE TITLE
Unable to use config file "Unknown content type in config file:"

### ISSUE THREAD

**Issue by tmikaeld** [jitsucom/jitsu#671]
## Description
Added config from example into file (only kept server section)

## Steps to reproduce

Add:

```
server:
  name: server.local.com
  port: 8081
  public_url: https://server.local.com
  log:
    path: /home/jitsu/data/logs
```

## Expected behavior

Config to work

## Actual behavior

"Unknown content type in config file: /home/jitsu/config.yml"
