### ISSUE TITLE
Installed instance metrics collection

### ISSUE THREAD

**Issue by jfk9w** [jitsucom/jitsu#767]
### Problem

It would be nice if we could collect metrics off of user-installed Jitsu instances.

#### Server

Introduce a metrics relay service which collects Prometheus metrics data and submits it to some HTTP endpoint periodically. The relay is enabled by default and no additional configuration is required.

```yaml
server:
  metrics:
    relay:
      disabled: false # optional, disables relay altogether
      url: https://cplane.jitsu.com/prometheus/relay # optional
      deployment_id: fssGtU # optional, is equal to cluster ID by default
      interval: 1m # optional
      timeout: 1s # optional
```

Metrics data is anonymized by default, but users willing to provide their personalized metrics may set `server.metrics.relay.deployment_id`. Sensitive label values are hashed (currently `source_id` and `destination_id`).

Docker image configuration:
* `JITSU_EXTENTED_TELEMETRY_DISABLED` – same as `server.metrics.relay.disabled`
* `JITSU_EXTENTED_TELEMETRY_DEPLOYMENT_ID` – same as `server.metrics.relay.deployment_id`

The relay sends HTTP POST requests to the specified URL with JSON body of the following structure:
```json
{
    "timestamp": 1623125..., // current time in millis
    "deploymentId": "my_deployment_id", // either cluster ID or deployment_id from configuration if specified
    "hostId": "my-host.domain.com", // hostname as detected by os.Hostname()
    "data": [
        // collected Prometheus data via prometheus.Gatherer.Gather() ([]*dto.MetricFamily)
    ]
}
```

Also add `source_type`, `source_tap` and `destination_type` labels to relevant Prometheus metrics (in task_executor.go `source_tap` will be empty for now).
