### ISSUE TITLE
eventnative runs at 100% cpu

### ISSUE THREAD

**Issue by s4ke** [jitsucom/jitsu#786]
## Environment

- **Deploy method**: `docker-compose.yml` modified as a docker swarm stack
- **Jitsu version**:  for instance `1.38.6`
- **OS**: `Ubuntu 20.04`
- **Cloud Provider**: Hetzner

## Description

The UI seems to work, but the container is causing one CPU to be pinned at 100% cpu usage.

![grafik](https://user-images.githubusercontent.com/719760/152039232-a8cf343a-d824-4070-a284-4bd7e8cba4a6.png)

## Steps to reproduce

Deploy using swarm stack:

```
version: '3.2'
services:
  jitsu:
    image: jitsucom/jitsu:1.38.6
    environment:
      - REDIS_URL=redis://redis.local:6379
      - USER_RECOGNITION_ENABLED=true
      - USER_RECOGNITION_REDIS_URL=redis://redis.users.recognition.local:6379
      - TERM=xterm-256color
      - CLUSTER_ADMIN_TOKEN=<snip>
    volumes:
      - /mnt-alias/volume_jitsu_data/configurator/data/logs:/home/configurator/data/logs
      - /mnt-alias/volume_jitsu_data/server/data/logs:/home/eventnative/data/logs
      - /mnt-alias/volume_jitsu_data/airbyte:/home/eventnative/data/airbyte
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jitsu_network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.volume_jitsu_data == 1
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        - "traefik.http.routers.jitsu-configurator.rule=Host(`<snip>`)"
        - "traefik.http.routers.jitsu-configurator.entrypoints=http"
        - "traefik.http.services.jitsu-configurator.loadbalancer.server.port=8000"
        - "traefik.http.routers.jitsu-configurator.service=jitsu-configurator"
        - "traefik.constraint-label=traefik-public"

  redis:
    image: redis:6.2.4-alpine
    volumes:
      - /mnt-alias/volume_jitsu_redis_data/data:/data
    deploy:
      placement:
          constraints: 
            - node.labels.volume_jitsu_redis_data == 1
    networks:
      jitsu_network:
        aliases:
          - redis.local

  redis_users_recognition:
    image: redis:6.2.4-alpine
    volumes:
      - /mnt-alias/volume_jitsu_redis_users_recognition/data:/data
    deploy:
      placement:
          constraints: 
            - node.labels.volume_jitsu_redis_users_recognition == 1
    networks:
      jitsu_network:
        aliases: 
          - redis.users.recognition.local


networks:
  jitsu_network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
```

configured Postgres:

![grafik](https://user-images.githubusercontent.com/719760/152039580-1aaa09ae-38af-43ce-8ad3-2c549a7c70e5.png)

## Expected behavior

Server is not pinned at 100% cpu usage on one core in idle.

## Actual behavior

Server is at 100% cpu in idle.
