### ISSUE TITLE
v8go: Memory leak on long lived contexts

### ISSUE THREAD

**Issue by ezradiniz** [jitsucom/jitsu#809]
## Environment

- **Deploy method**: `jitsucom/jitsu docker`
- **Jitsu version**:  `1.39.3`

## Description
Memory grows very fast and is never freed, possibly related to v8go.

## Steps to reproduce

Runs the server processing a high volume of events 

## Expected behavior

Free the memory

## Actual behavior

Memory is never freed

**Comment by vklimontovich** [comment]
I'm sorry that this is happening. Sometimes, Jitsu requires fine-tuning under heavy load to avoid growing memory consumption. Would you mind sharing:
 - Your Jitsu config
 - Events volume
 - What is your destination and source?

And what led you to believe that issue is connected with v8? 

Also, if you want we can help you to set up advanced telemetry so we would be able to see you anonymized stats. If you're interested, please join our [Slack](https://jitsu.com/slack) and ping me directly

**Comment by absorbb** [comment]
@ezradiniz Currently, the main memory consumer on setups with high volume of events – is inmemory queue for [Retroactive User Recognition](https://jitsu.com/docs/other-features/retroactive-user-recognition).
We are currently working on redesign of user recognition in https://github.com/jitsucom/jitsu/issues/805
that will stop relying on inmemory queue - that will help to prevent memory leak on high  volume of events.

Advanced telemetry that @vklimontovich  mentioned may help to get certain of what is causing memory leaks.

**Comment by ezradiniz** [comment]
Sorry for the late response.

I don't have the production configuration at the moment, but below is the Jitsu config that I used for local testing.

> NOTE: In the real configuration, we have multiple Redshift destinations (some are in mode batch), also we are using `USER_RECOGNITION_ENABLED=false`

<details>
  <summary>Jitsu Configuration (eventnative.yaml)</summary>

```yaml
server:
  name: test
api_keys:
  - id: my-api-id-1
    client_secret: my-client-secret
    server_secret: my-server-secret
    origins:
      - '*'
      - 'my-origin'
destinations:
  redshift:
    only_tokens:
      - my-api-id-1
    type: redshift
    mode: stream
    data_layout:
      transform: |-
        function getProperties() {
            return {
                url: $.url,
                ip: $.source_ip,
            };
        }

        const common = {
            JITSU_TABLE_NAME: $.event_type,
            ...getProperties(),
        };

        const events = [
            "my_event",
        ];

        if (events.includes($.event_type)) {
            return {
                ...common,
            };
        } else {
            return null;
        }
      table_name_template: test
      primary_key_fields:
        - eventn_ctx_event_id
    config:
      db: my-db
      host: my-redshift-host
      password: my-password
      username: my-username
      port: 5439
      schema: my-schema
meta:
  storage:
    redis:
      host: my-redis-host
      port: 6379
```
</details>

Steps to reproduce:

1) Start the Jitsu server with the config (yaml) above
2) Send a bunch of events to the Jitsu server, for example:
```bash
#!/bin/bash

set -ex

while true
do
  # This event will be skipped
  curl -XPOST --data '{"event_type": "bad_event", "url": "https://fake-url.com"}' 'http://localhost:8001/api.gr9ju?p_t8bpu=my-client-secret'
  sleep 0.05
done
```
3) Wait a while and watch the memory grow

Now repeat the same test, but with this change: 

```go
// ...
// DO NOT process the event
// res, err := ProcessEvent(function, event)
// close(processDone)
// if err != nil {
// 	vte.results <- err
// } else {
// 	vte.results <- res
// }
close(processDone)
vte.results <- nil
// ...
```
(Reference: https://github.com/jitsucom/jitsu/blob/master/server/templates/template_executor.go#L229)

The memory will be fine and will not grow forever.

When I run the same test in Jitsu `v1.38.6` there is no memory problem. 

That's why I assume the problem is related to v8go

This week I will try to post more info about it.
