### ISSUE TITLE
Unable to select streams in airbyte postgres integration

### ISSUE THREAD

**Issue by militarpancho** [jitsucom/jitsu#830]
## Environment

- **Deploy method**: `jitsucom/server docker` `docker-compose.yaml`
- **Jitsu version**:  `beta`
- **OS**: for instance `Ubuntu 20.04`
- **Cloud Provider**: `GCP`

## Description
A short description of the bug and its impact

When using configurator, it's possible, but when using `eventnative.yaml` config, i'm not being able to use `selected_streams` field:

```
[ERROR]: [postgres] Error initializing source of type airbyte: error creating [airbyte] driver for [all] collection: error marshalling object: json: unsupported type: map[interface {}]interface {}
```

**Comment by xtreding** [comment]
Hi @militarpancho! Would you mind providing your `sources` section from `eventnative.yaml` configuration (without credentials).

**Comment by militarpancho** [comment]
```
sources:
  postgres:
    type: airbyte
    destinations:
      - gjkz8ugi2my73kfhya0mh
    schedule: '@hourly'
    config:
      config:
        database: postgres
        host: 172.17.0.2
        password: *******
        port: 5432
        schemas:
        - public
        ssl: false
        username: postgres
      docker_image: source-postgres
      image_version: 0.4.6
      selected_streams:
        - name: company
          namespace: public
          sync_mode: full_refresh
 ```
