### ISSUE TITLE
Not able to spawn Airbyte connectors on Jitsu running on Kubernetes using DinD

### ISSUE THREAD

**Issue by shubham19may** [jitsucom/jitsu#863]
## Environment

- **Deploy method**: `jitsucom/jitsu docker`
- **Jitsu version**:  `latest`
- **OS**: `Linux`
- **Cloud Provider**: `AWS EKS`
- **Docker Params (if deployed with docker)**: Mounting all required file paths including airbyte & docker.sock

## Description
Trying to deploy Jitsu on kubernetes with docker as DinD mode mentioned in the issue https://github.com/jitsucom/jitsu/issues/545. 
The log says ❌ Airbyte integration is disabled: failed to inspect current docker container by containerID [jitsu]: Error: No such container: jitsu

## Steps to reproduce

This is the configuration i have used to create a run Jitsu on K8s.
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: jitsu
spec:
    selector:
        matchLabels:
            app: jitsu
    template:
        metadata:
            labels:
                app: jitsu
        spec:
            hostname: jitsu
            volumes:
                - name: jitsu
                  persistentVolumeClaim:
                      claimName: jitsu-claim
                - name: docker-graph-storage 
                  emptyDir: {}
            containers:
                - name: jitsu
                  image: jitsucom/jitsu:latest
                  imagePullPolicy: IfNotPresent
                  env:
                      - name: CONFIGURATOR_ADMIN_TOKEN
                        value: kwaTnRNzdgMZ5gqDUAf3vNupvKw8Q9yY
                      - name: SERVER_ADMIN_TOKEN
                        value: TKNu4iPuJcvhsdfX9ukFqF6VhXmtpc4j
                      - name: UI_AUTH_ACCESS_SECRET
                        value: 8ydWLwpRWnHnKPMFq24a2iBZcMoyMfYL
                      - name: UI_AUTH_REFRESH_SECRET
                        value: EtahBGriN99tGt5EXQtYDBtoiMVnyWmA
                      - name: REDIS_URL
                        value: redis://redis:15601
                      - name: DOCKER_HOST 
                        value: tcp://localhost:2375 
                  ports:
                      - containerPort: 8000
                - name: dind-daemon 
                  image: docker:dind
                  command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
                  securityContext: 
                      privileged: true 
                  volumeMounts: 
                    - mountPath: /home/configurator/data/logs
                      name: docker-graph-storage
                    - mountPath: /home/eventnative/data/logs/events
                      name: docker-graph-storage
                    - mountPath: /home/eventnative/data/logs
                      name: docker-graph-storage
                    - mountPath: /home/eventnative/data/airbyte
                      name: docker-graph-storage
                    - mountPath: "/var/run/docker.sock"
                      name: docker-graph-storage
                        
                
            initContainers:
                - name: init-jitsu
                  image: jitsucom/jitsu:latest
                  command: ['sh', '-c', 'set -x', 'chmod -R 777 /home/eventnative', 'chmod -R 777 /home/configurator']
                  volumeMounts:
                      - mountPath: /home/configurator/data/logs
                        name: docker-graph-storage
                      - mountPath: /home/eventnative/data/logs/events
                        name: docker-graph-storage
                      - mountPath: /home/eventnative/data/logs
                        name: docker-graph-storage
                      - mountPath: /home/eventnative/data/airbyte
                        name: docker-graph-storage
                      - mountPath: "/var/run/docker.sock"
                        name: docker-graph-storage
```

## Expected behavior

Expected behaviour is to successfully run Airbyte connectors on kubernetes in DinD or DooD modes.

## Actual behavior

Currently when Jitsu starts and i create a simple file (airbyte) source. It throws following error in logs : 

```
2022-03-16 20:33:06 [ERROR]: source-file-0.2.9-6b1b8385-2f21-400c-8c9a-1909cc2b4136 airbyte runner closing failed. Killing. Closing error: exit status 1
```

And when i press next after filling details of File connector, it throws following error : 

```
2022-03-16 20:33:49 [ERROR]: Error executing airbyte check:
	{"type": "LOG", "log": {"level": "FATAL", "message": "[Errno 2] No such file or directory: '/tmp/airbyte/7cda4ceffc75441495f5e826c23ccb89/8fda8740c9374561b9f9fbf486229556.json'\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\", line 127, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\", line 80, in run\n    self.configure_sentry(source_spec.connectionSpecification, parsed_args)\n  File \"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\", line 67, in configure_sentry\n    config = self.source.read_config(parsed_args.config)\n  File \"/usr/local/lib/python3.7/site-packages/airbyte_cdk/connector.py\", line 42, in read_config\n    with open(config_path, \"r\") as file:\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/airbyte/7cda4ceffc75441495f5e826c23ccb89/8fda8740c9374561b9f9fbf486229556.json'"}}
```

**Comment by viggin543** [comment]
@shubham19may 
Don't kill the messenger, It's only my personal opinion. 

I think that DnD and k8s are not things you should run in prod, for a myriad of reasons.

We installed Airbyte on k8s as is.
It's a much cleaner approach IMHO.

**Comment by shubham19may** [comment]
> @shubham19may Don't kill the messenger, It's only my personal opinion.
> 
> I think that DnD on k8s is not something you should run in prod, for a myriad of reasons.
> 
> We installed Airbyte on k8s as is. It's a much cleaner approach IMHO.

@viggin543 so basically you are only using Airbyte on K8s rather than Jitsu?

And you are suggesting we should only use Airbyte because its more clean?

**Comment by viggin543** [comment]
@shubham19may clean === safe, monitorable, scalble etc..

**Comment by absorbb** [comment]
The fix was committed to master. We are going to give it day or two of extra testing before releasing new hotfix image.

Also i've noticed few mistakes in config example you have provided. E.g. all volumes was mounted to dind-daemon container instead of jitsu. init-jitsu command wouldn't  run anything except of `set -x`

I suggest config example with fixes and simplifications, and explanation how jitsu - DinD - airbyte schema works:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsu
  labels:
    app: jitsu
spec:
  selector:
    matchLabels:
      app: jitsu
  template:
    metadata:
      name: jitsu
      labels:
        app: jitsu
    spec:
      hostname: jitsu
      volumes:
        - name: server-logs
          hostPath:
            path: /data/jitsu/server-logs
            type: DirectoryOrCreate
        - name: configutator-logs
          hostPath:
            path: /data/jitsu/configutator-logs
            type: DirectoryOrCreate
        - name: jitsu-workspace
          emptyDir: {}
        - name: docker-graph-storage 
          emptyDir: {}
      containers:
        - name: jitsu
          image: jitsucom/jitsu:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIGURATOR_ADMIN_TOKEN
              value: admin_token
            - name: SERVER_ADMIN_TOKEN
              value: admin_token
            - name: REDIS_URL
              value: redis://host.minikube.internal:6379
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: SERVER_VOLUMES_WORKSPACE
              value: /tmp/airbyte/
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /home/configurator/data/logs
              name: configutator-logs
            - mountPath: /home/eventnative/data/logs
              name: server-logs
            - mountPath: /home/eventnative/data/airbyte
              name: jitsu-workspace

        - name: dind-daemon
          image: docker:dind
          command: [ "dockerd", "--host", "tcp://127.0.0.1:2375" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: jitsu-workspace
              mountPath: /tmp/airbyte/

      initContainers:
        - name: init-jitsu
          image: jitsucom/jitsu:latest
          command: ["/bin/bash"]
          args: ['-c', 'sudo chmod -R 777 /home/eventnative; sudo chmod -R 777 /home/configurator']
          volumeMounts:
            - mountPath: /home/configurator/data/logs
              name: configutator-logs
            - mountPath: /home/eventnative/data/logs
              name: server-logs
```

### jitsu -> airbyte bridge through Docker-in-Docker

- Jitsu configured with SERVER_VOLUMES_WORKSPACE=/tmp/airbyte/
- Before Jitsu runs Airbyte source it generates config files and put them into `/home/eventnative/data/airbyte` directory
- `/home/eventnative/data/airbyte` directory mapped to **jitsu-workspace** named volume
- When Jitsu runs Airbyte source it uses command like `docker run -v SERVER_VOLUMES_WORKSPACE:/tmp/airbyte/ ... --config /tmp/airbyte/config.json` which translate to `docker run -v /tmp/airbyte/:/tmp/airbyte/ ... --config /tmp/airbyte/config.json`
- Since jitsu container have DOCKER_HOST=tcp://localhost:2375 airbyte source image actually runs inside dind-daemon container
- dind-daemon container have `/tmp/airbyte/` path mapped as **jitsu-workspace** named volume
- that is how through  **jitsu-workspace** named volume jitsu and airbyte source manage to interchange files

We will update docs with that information soon.
