### ISSUE TITLE
SSO - Automatic user provisioning

### ISSUE THREAD

**Issue by Flyover-ArtSk** [jitsucom/jitsu#887]
### Problem

Currently, we do not create a new user when logging in via SSO. It must be created manually through the API.

### Solution

It is necessary to automatically create a new user when authorizing via SSO and log in with this user.

### Implementation

Need to add a new parameter `autoProvision` to the SSO configuration with following structure:
```
"autoProvision": {
  "enable": true,
  "autoOnboarding": true
}
```

If `autoProvision.enable == true` - user will be created automatically after SSO authorization.
If `autoProvision.autoOnboarding == true` - not need to start the onboarding process to automatically created user.

**Comment by Flyover-ArtSk** [comment]
Done in https://github.com/jitsucom/jitsu/pull/892

New config example:
yaml
```yaml
sso:
  provider: 'boxyhq'
  auto_provision:
    enable: true
    auto_onboarding: true
  host: '__HOST__'
  tenant: '__TENANT__'
  product: '__PRODUCT__'
  access_token_ttl_seconds: 86400
```

env
```bash
export JITSU_SSO_CONFIG = '{"provider": "boxyhq","host": "__HOST__","tenant": "__TENANT__","product": "__PRODUCT__","access_token_ttl_seconds": 86400, "auto_provision": {"enable": true, "auto_onboarding": true}}'
```
