### ISSUE TITLE
Airbyte was not initialized: <nil> (#400)

### ISSUE THREAD

**Issue by rajaseg** [jitsucom/jitsu#961]
Hello Team,
Thank you very much for the project. I deployed the @jitsucom/jitsu image using docker compose. I am getting below error when I try to add the ```file``` source from Airbyte.

![image](https://user-images.githubusercontent.com/633479/184082360-5ea4a9be-e3cf-4309-ac53-5ddf85093af5.png)

docker-compose

```
version: "3.7"

services:
  jitsu:
    image: jitsucom/jitsu
    depends_on:
      - redis
    volumes:
      - /mnt/jitsu:/home/eventnative/data/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/jitsu_workspace:/home/eventnative/data/airbyte
    environment:
      - REDIS_URL=redis://redis:6379
      - USER_RECOGNITION_ENABLED=false
      - CLUSTER_ADMIN_TOKEN=secret
    networks:
      - caddy
    ports:
      - "8000:8000"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure  
    
  redis:
    image: redis:alpine
    volumes:
      - /mnt/redisdata:/data
    ports:
      - "6379:6379" 
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  jitsu:
    driver: "local"
  redisdata:
    driver: "local"
  jitsu_workspace:
    driver: "local"
networks:
  caddy:
    external: true
```

**Comment by absorbb** [comment]
@rajaseg 
```      - /mnt/jitsu_workspace:/home/eventnative/data/airbyte```
jitsu_workspace - is a named volume. 
Please try without adding /mnt/ path:
```      - jitsu_workspace:/home/eventnative/data/airbyte```

**Comment by rajaseg** [comment]
> jitsu_workspace

@absorbb, I have tried without /mnt path but got the same error.

![image](https://user-images.githubusercontent.com/633479/184088460-7955f700-817c-4f14-8cd6-3e42bf271651.png)

I configured GlusteFS as replicated volume for data availability throughout the docker swarm cluster. That's why I used the /mnt path to map container volumes.

**Comment by absorbb** [comment]
Can you please check application log during startup. It must explain why Airbyte was not initialized.
Look for `Airbyte integration is disabled` text

**Comment by rajaseg** [comment]
> Can you please check application log during startup. It must explain why Airbyte was not initialized. Look for `Airbyte integration is disabled` text

@absorbb, I found below error message in application logs.

![image](https://user-images.githubusercontent.com/633479/184101297-d8136d92-449d-45f1-ab0a-84fb885f8f62.png)

docker-compose

```
version: "3.7"

services:
  jitsu:
    image: jitsucom/jitsu
    depends_on:
      - redis
    volumes:
      - /mnt/jitsu:/home/eventnative/data/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jitsu_workspace:/home/eventnative/data/airbyte
    environment:
      - REDIS_URL=redis://redis:6379
      - USER_RECOGNITION_ENABLED=true
      - CLUSTER_ADMIN_TOKEN=secret
    networks:
      - caddy
    ports:
      - "8000:8000"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure  
    
  redis:
    image: redis:alpine
    volumes:
      - /mnt/redisdata:/data
    ports:
      - "6379:6379" 
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  jitsu:
    driver: "local"
  redisdata:
    driver: "local"
  jitsu_workspace:
    driver: "local"
networks:
  caddy:
    external: true
```

**Comment by absorbb** [comment]
Right way to mount would be:
```      - jitsu_workspace:/home/eventnative/data/airbyte```
jitsu_workspace is a name. not a path

**Comment by rajaseg** [comment]
> Right way to mount would be: ` - jitsu_workspace:/home/eventnative/data/airbyte` jitsu_workspace is a name. not a path

@absorbb, I changed the path to value, and everything working as expected.

Here is the final docker-compose file

```
version: "3.7"

services:
  jitsu:
    image: jitsucom/jitsu
    depends_on:
      - redis
    volumes:
      - /mnt/jitsu:/home/eventnative/data/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/home/eventnative/data/airbyte
    environment:
      - REDIS_URL=redis://redis:6379
      - USER_RECOGNITION_ENABLED=true
      - CLUSTER_ADMIN_TOKEN=secret
    networks:
      - caddy
    ports:
      - "8000:8000"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure  
    
  redis:
    image: redis:alpine
    volumes:
      - /mnt/redisdata:/data
    ports:
      - "6379:6379" 
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  jitsu:
    driver: "local"
  redisdata:
    driver: "local"
  workspace:
    name: jitsu_workspace
networks:
  caddy:
    external: true
```
