### ISSUE TITLE
WebHook http header content-type header not set

### ISSUE THREAD

**Issue by HassanMahmud** [jitsucom/jitsu#967]
## Environment

- **Deploy method**: 
Tried both cloud and heroku 

## Description
Content type http header cannot be set.

## Steps to reproduce
Create a http destination and add a 'Content-Type: application/json' to the http headers and use something like https://webhook.site/ to see the result of the destination. 

## Expected behavior
The content type set to application/json.

## Actual behavior
You can see the content type is empty.

**Comment by Alessar** [comment]
Hi @HassanMahmud.
Testing from the master shows the expected result.
```
destinations:
  my_webhook:
    type: webhook
    mode: stream
    config:
      url: https://webhook.site/<guid>
      method: POST
      headers:
        Content-Type: application/json
```
Please check the configuration and try to retest the behaviour.
Feel free to provide the version and part of the webhook configuration if the retesting shows a bad result.
